metadata_features:
        - sample
        - batch
        - age
        - cluster
        - Total_UMIs
        - log10UMI
        - num_genes_expressed
        - mito_ratio
        - cycle_phase
        - cycle_G1_score
        - cycle_G2M_score
        - cycle_S_score
        - cell_type
        - cellPattern1
        - cellPattern2
        - cellPattern3
        - cellPattern4
        - cellPattern5
        - cellPattern6
        - cellPattern7
        - cellPattern8       
        - cellPattern9
        - cellPattern10
        - cellPattern11
        - cellPattern12
        - cellPattern13
        - cellPattern14
        - cellPattern15
        - cellPattern16
        - cellPattern17
        - cellPattern18
        - cellPattern19
        - cellPattern20
        - cellPattern21
        - cellPattern22
        - cellPattern23
        - cellPattern24
        - cellPattern25
        - cellPattern26      
        - cellPattern27
        - cellPattern28
        - cellPattern29
        - cellPattern30
        - cellPattern31
        - cellPattern32
        - cellPattern33
        - cellPattern34
        - cellPattern35
        - cellPattern36
        - cellPattern37
        - cellPattern38
        - cellPattern39
        - cellPattern40
        - cellPattern41  
        - cellPattern42
        - cellPattern43
        - cellPattern44
        - cellPattern45
        - cellPattern46
        - cellPattern47
        - cellPattern48
        - cellPattern49
        - cellPattern50
continuous_features_to_fix:
        - Total_UMIs
        - log10UMI
        - num_genes_expressed
        - mito_ratio
        - cycle_G1_score
        - cycle_G2M_score
        - cycle_S_score
        - cellPattern1
        - cellPattern2
        - cellPattern3
        - cellPattern4
        - cellPattern5
        - cellPattern6
        - cellPattern7
        - cellPattern8       
        - cellPattern9
        - cellPattern10
        - cellPattern11
        - cellPattern12
        - cellPattern13
        - cellPattern14
        - cellPattern15
        - cellPattern16
        - cellPattern17
        - cellPattern18
        - cellPattern19
        - cellPattern20
        - cellPattern21
        - cellPattern22
        - cellPattern23
        - cellPattern24
        - cellPattern25
        - cellPattern26      
        - cellPattern27
        - cellPattern28
        - cellPattern29
        - cellPattern30
        - cellPattern31
        - cellPattern32
        - cellPattern33
        - cellPattern34
        - cellPattern35
        - cellPattern36
        - cellPattern37
        - cellPattern38
        - cellPattern39
        - cellPattern40
        - cellPattern41
        - cellPattern42
        - cellPattern43
        - cellPattern44
        - cellPattern45
        - cellPattern46
        - cellPattern47
        - cellPattern48
        - cellPattern49
        - cellPattern50
